"use client";

import { Dancing_Script, PT_Serif } from "next/font/google";
import { LanguageProvider } from "@/context/Language";
import "./globals.css";
import { AuthProvider } from "@/context/Auth";

const dancingScript = Dancing_Script({
    subsets: ["latin"],
    variable: "--font-dancing-script",
});

const ptSerif = PT_Serif({
    weight: ["400", "700"],
    subsets: ["latin"],
    variable: "--font-pt-serif",
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <title>Silhouette</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/app_logo.png" />
            </head>
            <body className={` ${dancingScript.variable} ${ptSerif.variable} antialiased`}>
                <AuthProvider>
                    <LanguageProvider>{children}</LanguageProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
