"use client";

import { Roboto } from "next/font/google";
import { LanguageProvider } from "@/context/Language";
import "./globals.css";

const roboto = Roboto({
    weight: ["400", "700"],
    subsets: ["latin"],
    variable: "--font-roboto",
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <title>TalkFlow</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/app_logo.png" />
            </head>
            <body className={`${roboto.variable} antialiased`}>
                <LanguageProvider>{children}</LanguageProvider>
            </body>
        </html>
    );
}
